### ISSUE TITLE
Incorrect evaluation of "Invalid Middle Configuration"

### ISSUE THREAD

**Issue by lbarral** [merpig/RubiksProgram#4] opened 2021-10-18 19:23 UTC
A diagonal stripe pattern with the 4x4x4 cube, which is legal, always yields "Invalid Middle Configuration" in the 'solver' mode.
Have a look at the following pictures:
https://photos.app.goo.gl/fbWYoYoFFe4XQY2x8

Those are opposing corners of the cube (like rotating 180º in the view axis)

Attempting to create that pattern in the Solver mode is not permitted.

**Comment by merpig** [comment] 2021-10-18 22:44
Interesting, I'll take a look and thank you for letting me know! Do you have an algorithm for that pattern I could use to test it out?

**Comment by lbarral** [comment] 2021-10-19 11:27
I have added some screenshots from an android app called ASolver, with the reverse solve, to the same google photos album.

**Comment by nvlashi** [comment] 2022-01-06 17:34
I'm also getting an "Invalid Middle Configuration" error on a valid 9x9 scramble.  
<img width="921" alt="Screen Shot 2022-01-06 at 12 33 30 PM" src="https://user-images.githubusercontent.com/1738617/148425557-288ffdc1-d2c0-4bcb-b682-136214c086f9.png">
<img width="902" alt="Screen Shot 2022-01-06 at 12 32 26 PM" src="https://user-images.githubusercontent.com/1738617/148425569-6bc52aef-7afb-4a89-9048-3a9e05e8039c.png">

**Comment by merpig** [comment] 2022-01-18 19:44
Been pretty busy recently, have had this on my list to fix and will get to it soon! I probably just need to simplify mapping stickers to the cube in the color picker.

**Comment by merpig** [comment] 2022-01-25 17:46
I believe the issue has now been resolved. A size parameter that was expected when evaluating middle pieces wasn't being passed. Correctly added the parameter and the 4x4 case now runs as intended. I would test the 9x9 but the images don't include all sides. I believe they only shows 5 of the sides as the bottom left in the top image and the top right in the bottom image are the same side. If the fix solves both issues correctly for y'all I will close the issue.

**Comment by nvlashi** [comment] 2022-01-25 18:46
Thanks.  I’ll give it a try and let you know.

**Comment by lbarral** [comment] 2022-01-25 19:34
I've tried the 4x4x4 using the https://merpig.github.io/RubiksProgram/ and it still ends up with the same message... is that version already containing the changes/fix? Or do I need to try somewhere else?

**Comment by merpig** [comment] 2022-01-25 20:11
React uses webpack you may need to hard refresh, or close and reopen browser for the webpack to update with changes. Basically, the app is cached so it can be used offline. So, if you download the app since it's a PWA it won't need internet access to open and use.
<img width="441" alt="update" src="https://user-images.githubusercontent.com/9353730/151052229-d3e9d117-75a1-4bfa-8aec-5b6f474f3f62.PNG">

** You'll know you have the update when there are arrows on the undo/redo buttons above the cube, I fixed that with the update as well

**Closed as completed** 2022-04-30 19:17 UTC

**Comment by llopness** [comment] 2024-11-24 17:14
I'm seeing the same issue with a 4x4x4 solve
![cube-solver_2](https://github.com/user-attachments/assets/eb78a3ef-64e7-4fd9-9976-f0d78441b4d3)
![cube-solver](https://github.com/user-attachments/assets/7287d161-d698-47a7-90a2-352fca4ce001)

**Comment by merpig** [comment] 2024-11-25 21:58
Looks like an older unfixed version of my site I let ruwix host. The version i have on github should have that fixed [deployed link](https://merpig.github.io/RubiksProgram)
